<?xml version="1.0" encoding="utf-8"?>
<RegattaConfig>
    <RegattaID>${regattaId}</RegattaID>
    <RegattaName>${name}</RegattaName>
    <CourseName>${courseName}</CourseName>
    <CentralLatitude>${latitude}</CentralLatitude>
    <CentralLongitude>${longitude}</CentralLongitude>
    <CentralAltitude>${altitude}</CentralAltitude>
    <UtcOffset>${utcOffset}</UtcOffset>
    <MagneticVariation>${magneticVariation}</MagneticVariation>
</RegattaConfig>